### ISSUE TITLE
Can a homie get some post endpoints?

### ISSUE THREAD

**Issue by jdaless** [tekulvw/modularsecurity#85]
I have the UI but still need the endpoints to:
- [x] Update a system 
- [x] Update a user
- [x] Hit the kill switch n a system
- [x] Add a device to a system
- [x] Add a secondary to a system
- [x] Remove a secondary of a system
- [x] Remove a device from a system
- [x] Toggle the status of a device on a system

I also need to be able to:
Get the secondaries of a system
